hyochan/react-native-nitro-sound

Example/android/app/src/main/java/com/dooboo/MainActivity.java, Example/android/build.gradle, Example/android/gradle.properties, Example/android/gradle/wrapper/gradle-wrapper.properties, README.md, android/build.gradle, package.json
Support #81 for `androidx` migration.
=> Androidx compatible

Example/ios/Podfile.lock, Example/package.json, Example/yarn.lock, ios/RNAudioRecorderPlayer.m, package.json
=> Release 2.4.4

Example/ios/Podfile.lock, Example/package.json, Example/src/components/screen/Intro.tsx, Example/yarn.lock, README.md
=> Fix broken example & fix seekToPlayer readme

android/src/main/java/com/dooboolab/RNAudioRecorderPlayerModule.java, index.ts
Fix poor record quality on android
=> add android record parameters

README.md
=> readme documentation updated: startRecorder function

README.md
=> Documenting meteringEnabled argument

ios/RNAudioRecorderPlayer.m
I found the reason, I fixed #197 and I'm using it.
Please release soon.
=> Fixed #197

CHANGELOG.md, Example/App.tsx, README.md, android/src/main/java/com/dooboolab.audiorecorderplayer/RNAudioRecorderPlayerModule.kt, package.json
Fix broken android default path.
Closes #283
=> Release 3.0.0-beta.3

CHANGELOG.md, Example/App.tsx, Example/ios/Podfile.lock, ios/RNAudioRecorderPlayer.swift, package.json
Closing https://github.com/hyochan/react-native-audio-recorder-player/milestone/1
=> Release 3.0.0

CHANGELOG.md, ios/RNAudioRecorderPlayer.swift, package.json
=> Allow file uri to play in `iOS`

CHANGELOG.md, ios/RNAudioRecorderPlayer.swift, issue_template.md, package.json
Hopefully resolve #304 
- Related to #300
=> Handle file path better

CHANGELOG.md, ios/RNAudioRecorderPlayer.swift, package.json
=> Set recording audio sesssion default to speaker

CHANGELOG.md, ios/RNAudioRecorderPlayer.swift, package.json
=> Fix unexpectedly found nil in swift

CHANGELOG.md, Example/App.tsx, Example/yarn.lock, android/src/main/java/com/dooboolab.audiorecorderplayer/RNAudioRecorderPlayerModule.kt, index.ts, package.json
Was poking around, heres a way that the player can automatically stop when done playing. Right now the user has to setup a playback listener and do that manually.
The approach I took was to unconditionally add an event listener when play is pressed, and if `addPlayBackListener` has been called, then we'll call that as apart of our event listener. This way, we can do some additional logic in our event listener (e.g check if duration === currentPosition), while still having only one event listener overall.
Another approach would of been to add a completely separate event listener for internal use only.
=> Stop player on completion

android/src/main/java/com/dooboolab.audiorecorderplayer/RNAudioRecorderPlayerModule.kt, index.ts, ios/RNAudioRecorderPlayer.swift
Close https://github.com/hyochan/react-native-audio-recorder-player/issues/371
=> fix: normalize seekToPlayer time argument

CHANGELOG.md, android/build.gradle, package.json, yarn.lock
=> Fix android build on sdk 31

ios/RNAudioRecorderPlayer.swift
Not tested much but seems ok
https://github.com/hyochan/react-native-audio-recorder-player/issues/306
=> RCTJSONStringify parse error json fix

Example/android/app/src/main/AndroidManifest.xml, Example/android/build.gradle, android/build.gradle
This PR upgrades  kotlin version to 1.6.0, compileSdkVersion and targetSdkVersion to 31 on android example
=> Upgrade kotlin version and sdk version on android

android/src/main/java/com/dooboolab.audiorecorderplayer/RNAudioRecorderPlayerModule.kt
according to docs: https://developer.android.com/reference/android/media/MediaRecorder
=> More fixes in #559

android/build.gradle
Fixes https://github.com/hyochan/react-native-audio-recorder-player/issues/574 
@hyochan
=> #574 - fix Android RN 0.73.0 support

ios/RNAudioRecorderPlayer.swift
Add a mechanism to handle recording interruptions caused by iOS external applications.
Related issues: [#170](https://github.com/hyochan/react-native-audio-recorder-player/issues/170) [#583](https://github.com/hyochan/react-native-audio-recorder-player/issues/583)
=> feature: handling iOS recording interruption events

android/src/main/java/com/dooboolab.audiorecorderplayer/RNAudioRecorderPlayerModule.kt, index.ts, ios/RNAudioRecorderPlayer.m, ios/RNAudioRecorderPlayer.swift
support to change playback speed!
=> feat: add support to change playback speed

NitroAudioRecorderPlayer.podspec
=> fix: xcodebuild with Static Linking (for Firebase)

.github/workflows/ci-ios.yml, example/android/app/src/main/java/audiorecorderplayer/example/MainApplication.kt, example/android/build.gradle, example/android/gradle/wrapper/gradle-wrapper.properties, example/ios/AudioRecorderPlayerExample/Info.plist, example/ios/Podfile.lock, example/package.json, yarn.lock
- Align deps via align-deps; Android SDK 36/Gradle 8.14.3
- Update MainApplication to 0.81 API; iOS pods refreshed
=> chore(example): upgrade RN to 0.81.1

android/src/main/java/com/margelo/nitro/audiorecorderplayer/AudioRecorderPlayer.kt, example/ios/Podfile.lock
Return file:// URIs on start/stop; handle file:// playback.
=> fix(android): return file:// URIs for recording and support file:// in playback
