hyochan/react-native-nitro-sound

ios/RNAudioRecorderPlayer.m

The path parameter of the method startRecord behaves as a path on Android, where you can pass for example 'sdcard/hello.mp4'. On iOS it was only supporting the fileName, this fix makes the function consistent between iOS and Android, both now can take a path.
Fixes #90

Makes path param in startRecord to behave as a path on iOS

---

ios/RNAudioRecorderPlayer.podspec

Updated the podspec to work with react native 0.60+. While installing I got an error from cocoapods because the homepage was not filled. Also noticed that the podspec was outdated as the version was still on `1.0.0` so I fixed that aswell.

Update podspec for RN 0.60

---

README.md

MainApplication.java instead MainActivity.java in README. May cause confusion for users doing a manual installation.

Fixed incorrect file manual installation on Android

---

ios/RNAudioRecorderPlayer.m

update:
add custom path for ios in `startPlayer` method. Currently, `startPlayer` only accepts file name with the default parent directory (Cache Directory). So I add the condition to check if `path` contains `file://` then use `path`, else append default parent directory into path file.

add custom path for ios

---

index.ts
ios/RNAudioRecorderPlayer.m

Issue:
currently, there is only one flag to define player playing or not. The issue is once user pauses audio player, then change audio player path/uri, the audio player play previous path/uri because audio player does not stop/unset properly.
So, in this PR I add new flag to define is player pause.
note: this PR also contains my previous PR related to `add custom path for ios` (https://github.com/dooboolab/react-native-audio-recorder-player/pull/168).

Handle stop once player is paused

---

ios/RNAudioRecorderPlayer.m

PR #168 fixed the possibility to add a custom path on iOS, but only for startPlayer, the same code is in startRecorder, so I replicated the change in that method also.

Replicate change of PR #168 into startRecorder

---

android/src/main/java/com/dooboolab/RNAudioRecorderPlayerModule.java
index.ts
ios/RNAudioRecorderPlayer.m
package.json

Adding optional volume tracking as part of RecordBackListener for both iOS and Android.
Implementation was inspired by https://github.com/jsierles/react-native-audio and https://github.com/jsierles/react-native-audio/pull/347
also fixed 1 minor bug - changed `"main": "index.js",` to `"main": "index.ts",` in package.json.
it's important to mention this changes the API (adding argument for startRecorder function)
can solve #73

Adding optional volume metering

---

ios/RNAudioRecorderPlayer.m

When starting to record while playing music It was constantly playing the music from the phone music and not Bluetooth earpiece.
Found that adding AVAudioSessionCategoryOptionAllowBluetooth option solves this

Play music in bluetooth earpiece while recording

---

android/build.gradle

running mergeExtDexDebugAndroidTest task failed. fixed it as described [here](https://stackoverflow.com/questions/49512629/default-interface-methods-are-only-supported-starting-with-android-n/49525685#49525685) and implemented [here](https://github.com/proyecto26/react-native-inappbrowser/pull/146)

fixing mergeExtDexDebugAndroidTest task

---

android/src/main/java/com/dooboolab/RNAudioRecorderPlayerModule.java

The mediarecorder on android fails to stop when recording time is less than a second, causing this "stop failed" error to show.
fixes #203
fixes #199

Add try catch block on mediaRecorder.stop()

---

README.md

When I check android part of the package there is this code
```
public void onCompletion(MediaPlayer mp) {
/**
* Send last event
*/
WritableMap obj = Arguments.createMap();
obj.putInt("duration", mp.getDuration());
obj.putInt("current_position", mp.getDuration());
sendEvent(reactContext, "rn-playback", obj);
/**
* Reset player.
*/
Log.d(TAG, "Plays completed.");
mTimer.cancel();
mp.stop();
mp.release();
mediaPlayer = null;
}
```
Which makes mediaPlayer null when playing is ended. So if we write below code to onStartPlay it will try to stop mediaPlayer that is already null and its will give warning "mediaPlayer is null".
if (e.current_position === e.duration) {
console.log('finished');
this.audioRecorderPlayer.stopPlayer();
}

onStartPlay unnecessary code

---

android/src/main/java/com/dooboolab/RNAudioRecorderPlayerModule.java

I faced a case that the app crashed if I try to start recording while another app is using microphone, app is crashing and I can't catch the error so I inform the user that some thing is happening.
when I traced the error I found that there is an error in stop record function but because there is not promise reject in the catch, so I can't get the error my side.
so I added this promise reject statement in android , and I hope to be able to add similar thing to ios n the future.

Add promise reject in stop record

---

index.ts
ios/RNAudioRecorderPlayer.m

This PR is related to issue #264
The keys of `AVLinearPCMBitDepthKeyIOSType` are named `'bit8'`, `'bit16'`, and so on because the others names (as shown below) that I come up with will cause parsing to fail.
```ts
'8-bit' // Originally intended
'8bit'  // Without dash
'bit8'  // Alphabet as first character
```
Since according to [the docs](https://developer.apple.com/documentation/avfaudio/avlinearpcmbitdepthkey?language=objc), the accepted values are one of 8, 16, 24, and 32 only, I figured it'd be logical to make it an enum instead of a `number` type.
Also, I made this PR from my own `master` branch after forking it since I'm unable to find a `dev` branch as mentioned in `CONTRIBUTING.md`.

Support for Linear PCM format settings

---

CHANGELOG.md
Example/App.tsx
Example/android/build.gradle
README.md
android/src/main/java/com/dooboolab.audiorecorderplayer/RNAudioRecorderPlayerModule.kt
index.ts
ios/RNAudioRecorderPlayer.h
ios/RNAudioRecorderPlayer.m
ios/RNAudioRecorderPlayer.swift
package.json

- Add `resumeRecorder` and `pauseRecorder` features.
- **Caveat**: Android now requires min sdk of `24`.
- Renamed listener callback variables from `snake_case` to `camelCase`.
* Below are return types.
```ts
export type RecordBackType = {
isRecording?: boolean;
currentPosition: number;
currentMetering?: number;
};
export type PlayBackType = {
isMuted?: boolean;
currentPosition: number;
duration: number;
};
```
Closes #15
Closes #268 
Co-authored-by: PatrickNies <patrick.nies@waysofsolutions.de>

Ability to pause and resume recording

---

android/src/main/java/com/dooboolab.audiorecorderplayer/RNAudioRecorderPlayerModule.kt

When compiling the project with the following config:
```
compileSdkVersion = 30
targetSdkVersion = 30
```
An error occurs while trying to make a build for android. Its message is the following:
```
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
e: <project-path>/node_modules/react-native-audio-recorder-player/android/src/main/java/com/dooboolab.audiorecorderplayer/RNAudioRecorderPlayerModule.kt: (120, 41): Type mismatch: inferred type is Runnable? but Runnable was expected
e: <project-path>/node_modules/react-native-audio-recorder-player/android/src/main/java/com/dooboolab.audiorecorderplayer/RNAudioRecorderPlayerModule.kt: (138, 45): Type mismatch: inferred type is Runnable? but Runnable was expected
e: …
```

Add optional wrappers to support android sdk 30

---

index.ts

The types for both listener functions were incorrect, causing a typescript error demonstrated here: https://github.com/hyochan/react-native-audio-recorder-player/issues/309
This simply updates the signatures of the function to take in a callback function (that accepts a parameter of type `RecordBackType` or `PlayBackType`) and also adds some name changes

Update types in listener functions

---

ios/RNAudioRecorderPlayer.m

How to reproduce:
- Start player
- Call `seekToPlayer` with any positive number (e.g. `4000`)
- Actual result: the player sought to 0 (the song is played from the start).
- Expected result: the player seeks to 4 seconds.
My Environment:
- Simulator: iPhone 12 Pro, iOS 14.4
- React native 0.64.1

[iOS] Fix seekToPlayer method: it always seeked to 0.

---

CHANGELOG.md
ios/RNAudioRecorderPlayer.swift
package.json

[Bugfix/iOS] Fix crash when stopping recorder when metering is enabled.
- Resolve [#297](https://github.com/hyochan/react-native-audio-recorder-player/issues/297)

Resolve #297 (3.0.8)

---

ios/RNAudioRecorderPlayer.swift

Its currently impossible to select the `opus` encoding on iOS.

Impossible to select opus encoding on `iOS`

---

RNAudioRecorderPlayer.podspec
package.json
yarn.lock

This PR contemplates the addition of a minimal target for the ios_deployment_target, necessary for the pods. This resolves the issue #331

Fix minimum iOS deployment target

---

android/src/main/java/com/dooboolab.audiorecorderplayer/RNAudioRecorderPlayerModule.kt

There is an issue in android that when you stop recording, native exception is thrown  `println needs a message in android`
[Here](https://stackoverflow.com/questions/6018633/nullpointerexception-println-needs-a-message-in-android) is more info about this issue
also [this](https://github.com/hyochan/react-native-audio-recorder-player/issues/283)

fix println needs a message in android

---

README.md

The functions that remove the listeners were not documented, however the existed in the code

Update readme with functions to remove listeners

---

ios/RNAudioRecorderPlayer.swift

I'm suggesting this change because I ran into an issue where I couldn't hear the audio when playing if this audio had been recorded in a previous session of the app, but after recording a new audio then the others that had no sound before start to play normally.
After making this change to the Swift file the problem was solved and now I can listen to audios from the file system without having to start a recording first.

iOS - set AVAudioSession active before startPlayer

---

ios/RNAudioRecorderPlayer.swift

There was a bug in our project.
When you start recording but there is some work with sound in the same time somewhere in app,
audioRecorder looks like successfully started, but it isn't, no any updates from addRecordBackListener().
Debugging the swift code i have noticed that `audioRecorder.record()` returns false in that case.
Also, if you check `audioRecorder.isRecording` it is also false.
link to docs:
https://developer.apple.com/documentation/avfaudio/avaudiorecorder/1388252-record

Check if recording actually started

---

android/src/main/java/com/dooboolab.audiorecorderplayer/RNAudioRecorderPlayerModule.kt

When `WRITE_EXTERNAL_STORAGE` is already granted but not `RECORD_AUDIO` (or vice-versa), `startRecorder` will stop asking permission for `RECORD_AUDIO` as today a "and" is used instead of a "or" condition.
If user denies one of them, next call to `startRecorder` will lead to a hard crash with following stacktrace (if user still denies it):
java.lang.RuntimeException: setAudioSource failed.
at android.media.MediaRecorder.setAudioSource(Native Method)
at com.dooboolab.audiorecorderplayer.RNAudioRecorderPlayerModule.startRecorder(RNAudioRecorderPlayerModule.kt:62)
at java.lang.reflect.Method.invoke(Native Method)

Fix permission request when one is already granted

---

index.ts
ios/RNAudioRecorderPlayer.m
ios/RNAudioRecorderPlayer.swift

This PR adds basic header support for iOS. I still need to do some more testing, but wanted to post early here so others could try it out.
This closes https://github.com/hyochan/react-native-audio-recorder-player/issues/356 and https://github.com/hyochan/react-native-audio-recorder-player/issues/400.

iOS network header support

---

package.json
yarn.lock

I tried to run the Example locally, but got an issue related to `flowgen` which has been fixed with the latest version ([PR link](https://github.com/joarwilk/flowgen/pull/157) )
So I just updated the `flowgen` version
This will allow to use `yarn build` locally, and should also fix the failing build action on the `3.3.0` release
PS: also I noticed that the contributing guide say that we should do the changes in the `dev` branch, but it looks like it does not exist anymore

chore: upgrade flowgen package

---

README.md
index.ts
ios/RNAudioRecorderPlayer.swift

I had the need to use measurement mode while recording background audio.  I thought others may have similar needs.  This PR adds a new mode setting for ios.  
Thanks for the great lib!  Please let me know if I need to adjust this PR in any way.

New AVModeIOS audio setting

---

ios/RNAudioRecorderPlayer.swift

If I use this module to record some audio, and then try to play it back, I get the following error in the console.
```
2022-01-13 11:32:50.087002-0800 hilokal[4898:1045246] NSURLConnection finished with error - code -1002
```
I think this error was introduced in this PR: https://github.com/hyochan/react-native-audio-recorder-player/pull/405
This PR changes the AVURLAsset constructor back to use `audioFileURL`, as it did previously.

Fix playback of local files in iOS

---

Example/App.tsx
index.ts

Start record -> Pause record -> Stop record -> Start record again -> Pause record -> __Cannot pause record__ because `_hasPausedRecord` is still `true`
Before:
https://user-images.githubusercontent.com/31266357/172039275-9911439f-9dd3-4b3d-a7bb-71da12fb818a.mov
After:
https://user-images.githubusercontent.com/31266357/172039295-57fd9d05-26c7-44b0-a0de-b213ea41948b.mov

Fix #361: cannot pause recording after recorded once

---

android/src/main/java/com/dooboolab.audiorecorderplayer/RNAudioRecorderPlayerModule.kt

Fixes https://github.com/hyochan/react-native-audio-recorder-player/issues/497 by detecting if built using Android 13+ and only checking for the `RECORD_AUDIO` permission if so

#497 - Update Android permissions check for Android 13+

---

Example/App.tsx
ios/RNAudioRecorderPlayer.h
ios/RNAudioRecorderPlayer.swift

Comming from https://github.com/hyochan/react-native-audio-recorder-player/discussions/479, I'm trying to handle error with [audioPlayerDecodeErrorDidOccur:error](https://developer.apple.com/documentation/avfaudio/avaudioplayerdelegate/1387676-audioplayerdecodeerrordidoccur)
However, it looks like it is not catching any error from remote URL

chore: attempt on handling ios audio decode err

---

android/src/main/java/com/dooboolab.audiorecorderplayer/RNAudioRecorderPlayerModule.kt
index.ts
ios/RNAudioRecorderPlayer.swift

- add `bitRate` to iOS (default: 128000, same as Android)
- add `audioChannels` to Android (default: 2, same as iOS)

feat: add bitrate to ios and audio channels to android

---

android/src/main/java/com/dooboolab.audiorecorderplayer/RNAudioRecorderPlayerModule.kt

Hello, If the version of device is Android 10 or higher, no longer need the "write external storage" permission.
You can read more by following this link:
https://developer.android.com/about/versions/11/privacy/storage#permissions-target-11
>Keep in mind that, on devices that run Android 10 (API level 29) or higher, your app can contribute to well-defined media collections such as MediaStore.Downloads without requesting any storage-related permissions. Learn more about how to [request only the necessary permissions](https://developer.android.com/training/data-storage/shared/media#request-permissions) when working with media files in your app.
resolve #544

fix(android): update max sdk version for write external storage

---

README.md
android/build.gradle

Add kotlin-gradle-plugin to buildscript.dependencies.
Users no longer need to add Kotlin-related code to the build.gradle during the installation process.

chore(android): add kotlin-gradle-plugin

---

android/src/main/java/com/dooboolab.audiorecorderplayer/RNAudioRecorderPlayerModule.kt

probably fixes https://github.com/hyochan/react-native-audio-recorder-player/issues/557

Fix MediaPlayer Position Access Issue

---

ios/RNAudioRecorderPlayer.swift

When play a remote file on iOS, `currentPosition` may never get to `duration`, which makes it difficult to know whether the playing is end.
Add an observer to native player end event, and in that observer, force trigger another playback event, where `currentPosition` is set to be `duration`. Note that at this moment, `playerItem.currentTime` is still smaller than `duration`, so we cannot use that value.
may fix #328

fix(ios): currentPosition and duration may never equal during playing

---

android/src/main/java/com/dooboolab.audiorecorderplayer/RNAudioRecorderPlayerModule.kt

mTimer!!.cancel() was causing a crash when the URL was not a valid audio file. Have changed it to mTimer?.cancel(). Example: audioRecorderPlayer.startPlayer('https://www.google.com')

Fix crash for invalid audio URL

---

android/src/main/java/com/dooboolab.audiorecorderplayer/RNAudioRecorderPlayerModule.kt
index.ts
ios/RNAudioRecorderPlayer.swift

The purpose of this PR is to support chunked transfer-encoded HTTP requests, such as those returned from OpenAI and ElevenLabs Text-to-speech APIs.
Since these http requests don't contain a content-length, we can't rely on the duration to determine when they have finished.

Add isFinished to rn-playback event

---

.eslintrc.js
.github/workflows/code-review.yml
Example/.eslintrc.js
Example/.vscode/settings.json
Example/components/uis/Button.tsx
Example/package.json
Example/yarn.lock
package.json
yarn.lock

https://www.youtube.com/watch?v=sZoh0aLXq5g&list=PL9_jwgDt7c4lzyqj71w8wstuO35ZubsdF

ci: code-review gpt

---

ios/RNAudioRecorderPlayer.swift

There were a few race conditions in the multithreaded code in RNAudioRecorderPlayer.swift.
`self.recordTimer` is set from the main thread. If caller invokes `startRecoder` and then subsequently `stopRecorder`, there is no guarantee that `self.recordTimer` will be set in time. This will result in "ghost" rn-recordback events being sent to the React Native thread.
To resolve this, this PR creates the timers on the react-native bridge thread, and then manually adds them to the main thread's run loop.
`self.audioRecorder` has a similar issue. It's created on the main thread, but then `stopPlayer` checks its value on the bridge thread. To resolve the race condition here, this PR dispatches the check on the main thread

Fix race conditions in iOS

---

android/src/main/java/com/dooboolab.audiorecorderplayer/RNAudioRecorderPlayerModule.kt
index.ts
ios/RNAudioRecorderPlayer.swift

I am using this library to record ogg/opus files, however, the default file name was always "sound.mp4" or "sound.m4a", regardless of the audio format.
To fix this, I tried passing in a custom path to startRecord, with the correct file extension, however a native extension is required to get the proper path to the cache directory on Android.
Since a native modification is required anyway, I decided to modify this module to just pick a reasonable default file extension for the giving audio format.
I also added the proper OGG / OPUS types for Android to index.ts. These types are supported as of apiVersion 29.

Assign default file extension based on audio format

---

android/src/main/java/com/dooboolab.audiorecorderplayer/RNAudioRecorderPlayerModule.kt
index.ts

It's common for either `MediaRecorder.start()` or `MediaRecorder.prepare()` to fail if the device doesn't support the requested codec, or there is some problem with the arguments.
Currently, if this happens, the recorder is left in an invalid state:
If an error occurs, this._isRecording is still set to `true`, which is incorrect. This PR will catch an error and reset this boolean to `false`
If an error occurs,  `this.mediaRecorder` will be set to partially or incorrectly initialized object. The next time `startRecord()` is called, this stale object will be reused, which caused a secondary (and more confusing) error.
To fix this, `startRecord` will catch any initialization error and reset `this.mediaRecorder` to null.

If startRecorder fails, the recorder is left in an invalid, unrecoverable state

---

ios/RNAudioRecorderPlayer.swift

This PR addresses an issue that seems to have appeared with React Native `0.79.0` and onwards, related to how RN loads native modules I believe and how it's expected that their internal methods are meant to be executed. 
I can confirm that the issue is happening on `0.79.3` specifically on iOS, new architecture (have not tested on the old one).
Namely, each time `startRecording` is invoked it is going to fail about 70% of the time with an ambiguous error that requires further inspection. 
The line that actually fails is [this one here](https://github.com/hyochan/react-native-audio-recorder-player/blob/97f6012c1a0b4c0fe8808d7743a8f9a57772aeff/ios/RNAudioRecorderPlayer.swift#L267). More often than not, this should happen if:
- The `audioSession` is not active or configured properly
- …

fix: RN 0.79 audio recording failing most of the time

---

ios/RNAudioRecorderPlayer.swift

I was only able to reproduce this crash once, but I took a screenshot:
The root cause is that `audioPlayer` is set to nil on the react-native thread, not the main thread. So, even though we change for nil on line 338, there's no guarantee it's still not nil on line 340.
This PR will wrap the `audioPlayer = nil` mutation in `DispatchQueue.main.async`.
I also changed the time observer to keep a weak reference to self, because the apple docs state this is important to prevent a retain cycle: https://developer.apple.com/documentation/avfoundation/avplayer/1385829-addperiodictimeobserverforinterv?language=swift

Fix race condition that was causing a crash in time observer

---

android/src/main/java/com/margelo/nitro/audiorecorderplayer/AudioRecorderPlayer.kt
example/src/App.tsx

Fixes #693 - `stopRecorder` now returns the actual file path instead of "Recorder stopped"
- Start recording on Android
- Stop recording
- Verify the returned value is the file path (e.g., `/data/user/0/com.x/files/sound_1756843050671.mp4`)

fix(android): return file path from stopRecorder
